name: Feature request
description: Suggest an idea or enhancement for flutter_monaco
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the problem and the proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or other context.
    validations:
      required: false
